/**
 * sheetsClient.js
 * Provides an authenticated Google Sheets API client.
 *
 * Supports two authentication modes (tried in order):
 *
 *   1. Service Account JSON key  →  set GOOGLE_SERVICE_ACCOUNT_KEY env var
 *      (full JSON on one line)
 *
 *   2. Application Default Credentials (ADC)  →  no env var needed.
 *      Run once:  gcloud auth application-default login
 *      Useful when org policy blocks service account key downloads.
 *
 * In MOCK_MODE=true this module is never imported.
 */

import { google } from 'googleapis';

const SHEETS_SCOPE = 'https://www.googleapis.com/auth/spreadsheets';
const DRIVE_SCOPE  = 'https://www.googleapis.com/auth/drive';

let _sheetsClient = null;

/**
 * Returns a singleton authenticated Google Sheets client.
 * @returns {import('googleapis').sheets_v4.Sheets}
 */
export function getSheetsClient() {
  if (_sheetsClient) return _sheetsClient;

  const auth = buildAuth([SHEETS_SCOPE]);
  _sheetsClient = google.sheets({ version: 'v4', auth });
  return _sheetsClient;
}

/**
 * Returns a singleton authenticated Google Drive client.
 * @returns {import('googleapis').drive_v3.Drive}
 */
export function getDriveClient() {
  const auth = buildAuth([SHEETS_SCOPE, DRIVE_SCOPE]);
  return google.drive({ version: 'v3', auth });
}

/**
 * Builds a GoogleAuth instance.
 *
 * Priority:
 *   1. GOOGLE_SERVICE_ACCOUNT_KEY env var (JSON string)
 *   2. Application Default Credentials (gcloud auth application-default login)
 *
 * @param {string[]} scopes
 * @returns {import('google-auth-library').GoogleAuth}
 */
function buildAuth(scopes) {
  // Mode 1: Service account key JSON
  const keyJson = process.env.GOOGLE_SERVICE_ACCOUNT_KEY;
  if (keyJson && keyJson.trim()) {
    let credentials;
    try {
      credentials = JSON.parse(keyJson);
    } catch {
      throw new Error(
        'GOOGLE_SERVICE_ACCOUNT_KEY is set but is not valid JSON. ' +
        'Ensure the entire service account JSON is on a single line.'
      );
    }
    return new google.auth.GoogleAuth({ credentials, scopes });
  }

  // Mode 2: OAuth2 refresh token (generated by get-token.js)
  const clientId     = process.env.GOOGLE_CLIENT_ID;
  const clientSecret = process.env.GOOGLE_CLIENT_SECRET;
  const refreshToken = process.env.GOOGLE_REFRESH_TOKEN;
  if (clientId && clientSecret && refreshToken) {
    const oauth2 = new google.auth.OAuth2(clientId, clientSecret, 'http://localhost:8085/');
    oauth2.setCredentials({ refresh_token: refreshToken });
    return oauth2;
  }

  // Mode 3: Application Default Credentials (gcloud auth application-default login)
  return new google.auth.GoogleAuth({ scopes });
}
